#!/usr/bin/env php
<?php

use unionco\syncdb\SyncDb;
use unionco\syncdb\Model\SshInfo;
use unionco\syncdb\Model\Scenario;
use unionco\syncdb\Service\Config;
use unionco\syncdb\Model\DatabaseInfo;
use unionco\syncdb\Service\DatabaseSync;

require __DIR__ . '/vendor/autoload.php';

$path = '/Users/abry/Union/Sites/craft-plugin-host.com/config/syncdb.php';
// define('SYNCDB_CONFIG_PATH', __DIR__ . '/config.json');

$config = (require $path);
$config['common']['localWorkingDir'] = '/Users/abry/Union/Sites/craft-plugin-host.com';
$s = new SyncDb();
var_dump($s->dumpConfig($config, 'production'));

// $config = Config::parseConfig(SYNCDB_CONFIG_PATH, 'staging');

// $ssh = SshInfo::fromConfig($config);

// $remoteDb = DatabaseInfo::remoteFromConfig($config, $ssh);
// $localDb = DatabaseInfo::localFromConfig($config);

// /** @var DatabaseSync */
// $dbSyncService = SyncDb::$container->get('dbSync');

// $scenario = new Scenario('Sync Database', $ssh);
// $scenario = $dbSyncService->dumpDatabase($scenario, $remoteDb);

// $scenario = $dbSyncService->importDatabase($scenario, $localDb);

// echo $scenario->preview();
// $scenario->run();
// echo $scenario->preview(); die;
// SyncDb::$container->get(DatabaseSync::class)->dumpDatabase($ssh, $db);
