# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    app.dbSync:
      class: unionco\syncdbService\DatabaseSync
      public: true
    # app.validator:
    #   class: unionco\syncdbService\Validator
    #   public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # unionco\syncdb:
    #     resource: '../src/Service/*'
    #     exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
    unionco\syncdbService\DatabaseSync: '@app.dbSync'
    # unionco\syncdbService\ValidatorInterface: '@app.validator'
